[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap [fugitive]    <Nop>
nmap     <Leader>g [fugitive]
nnoremap <silent> [fugitive]s :<C-U>Git<CR>
nnoremap <silent> [fugitive]d :<C-U>Gdiffsplit<CR>
nnoremap <silent> [fugitive]b :<C-U>Git blame<CR>
nnoremap <silent> [fugitive]c :<C-U>Git commit<CR>
'''

[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = '''
nnoremap <silent> <Leader>h :<C-U>GundoToggle<CR>
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\	'_' : {
\		'runner' : 'vimproc',
\		'runner/vimproc/updatetime' : 60,
\		'outputter/buffer/opener': '%{winwidth(0) * 2 < winheight(0) * 5 ? "" : "vertical"} rightbelow new',
\	},
\	'markdown' : {
\		'outputter' : 'browser',
\		'type': 'markdown/pandoc',
\		'cmdopt': '--mathml -c ~/.pandoc/github.css',
\	}
\}
nnoremap <silent> <Leader>r :QuickRun -mode n<CR>
vnoremap <silent> <Leader>r :QuickRun -mode v<CR>
'''
