[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
hook_add = '''
nnoremap [ddu]    <Nop>
nmap     <Leader>u [ddu]
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
hook_source = '''
call ddu#custom#patch_global({
    \ 'ui': 'ff',
    \ })
'''
[plugins.ftplugin]
ddu-ff = '''
nnoremap <buffer><silent> <CR>
\ :<C-U>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> <Space>
\ :<C-U>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> i
\ :<C-U>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent> q
\ :<C-U>call ddu#ui#ff#do_action('quit')<CR>
'''
ddu-ff-filter = '''
inoremap <buffer><silent> <CR>
\ <Esc>:<C-U>close<CR>
nnoremap <buffer><silent> <CR>
\ :<C-U>close<CR>
nnoremap <buffer><silent> q
\ :<C-U>close<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'
hook_add = '''
nnoremap <silent> [ddu]f :<C-U>Ddu<Space>file<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'
hook_source = '''
call ddu#custom#patch_global({
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \     },
    \   }
    \ })
'''

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'
hook_source = '''
call ddu#custom#patch_global({
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   }
    \ })
'''
