[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
let g:unite_enable_start_insert=1

nnoremap [unite]    <Nop>
nmap     <Space>u [unite]

nnoremap <silent> [unite]<CR> :<C-u>Unite<CR>
nnoremap <silent> [unite]f    :<C-u>Unite<Space>file<Space>file/new<CR>
nnoremap <silent> [unite]p    :<C-u>Unite<Space>file_rec/async:!<CR>
nnoremap <silent> [unite]b    :<C-u>Unite<Space>buffer<CR>
nnoremap <silent> [unite]l    :<C-u>Unite<Space>line<CR>
nnoremap <silent> [unite]t    :<C-u>Unite<Space>tab<CR>
nnoremap <silent> [unite]g    :<C-u>Unite<Space>grep:.<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
hook_add = '''
nnoremap <silent> [unite]u    :<C-u>Unite<Space>file_mru<CR>
'''

[[plugins]]
repo = 'Shougo/unite-build'

[[plugins]]
repo = 'Shougo/unite-outline'
hook_add = '''
nnoremap <silent> [unite]o    :<C-u>Unite<Space>outline<CR>
'''

[[plugins]]
repo = 'Shougo/neossh.vim'
